version: "2"
services:
    web:
        container_name: StatusPage
        build: .
        command: npm run start
        volumes:
            - ./services.json:/app/services.json
            - ./config.json:/app/config.json
        ports:
            - "3000:3000"
